<?php
namespace Like2biz\Bundle\GoogleBundle\OAuth2\Response;

/**
 * RFC6749 OAuth2 authorization response interface.
 *
 * If the resource owner grants the access request, the authorization
 * server issues an authorization code and delivers it to the client.
 *
 * @see http://tools.ietf.org/html/rfc6749#section-4.1.2
 * @author Alexander Sergeychik
 */
interface AuthorizationResponseInterface {

	const PARAMETER_CODE = 'code';
	
	/**
	 * The authorization code generated by the
	 * authorization server.
	 *
	 * @return string
	 */
	public function getCode();

	/**
	 * The exact value received from the client.
	 * OPTIONAL if the "state" parameter was present in the client authorization request
	 *
	 * @return string|null
	 */
	public function getState();

}
